# Generated by Django 3.2.3 on 2022-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('resume', models.TextField()),
                ('raw_html', models.TextField()),
                ('clean_resume', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
