# Generated by Django 3.2.3 on 2022-06-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumedata',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='clean_resume',
            new_name='Clean_Resume',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='raw_html',
            new_name='Raw_html',
        ),
        migrations.RenameField(
            model_name='resumedata',
            old_name='resume',
            new_name='Resume',
        ),
    ]
